#! /bin/bash

set -e

if [ -z "$1" ] ; then
    echo "Please provide the contract to run as parameter." 1>&2
    echo "Example usage: $0 eopsin" 1>&2
    exit
fi
DIR="contracts/$1"
if [ ! -d "$DIR" ] ; then
    echo "$DIR does not exist." 1>&2
    exit
fi

(cd "$DIR" && ./bench_all)